# Generated by Django 5.1.1 on 2024-09-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='time_on_page',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
