# Generated by Django 5.1.1 on 2024-09-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pageview_session_key_pageview_time_on_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('contact_submissions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
