# Generated by Django 5.1.1 on 2024-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailyaggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='avg_time_on_page',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='bounce_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='new_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='top_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
