# Generated by Django 5.1.1 on 2024-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_dailyaggregate_avg_time_on_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyaggregate',
            name='conversion_rate',
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='conversions',
            field=models.IntegerField(default=0),
        ),
    ]
