# Generated by Django 4.1.13 on 2024-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_image_gallery_image1_gallery_image10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
