# Generated by Django 4.1.13 on 2024-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_home_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_image11',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_image12',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
