# Generated by Django 4.1.13 on 2024-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
