# Generated by Django 4.1.13 on 2024-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_home_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.AddField(
            model_name='home',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
