# Generated by Django 5.1.1 on 2024-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
