# Generated by Django 5.1.1 on 2024-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
