# Generated by Django 5.1.1 on 2024-10-19 16:11

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_home_call_to_action_alter_home_main_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to='services/'),
        ),
    ]
