# Generated by Django 5.1.1 on 2024-10-21 08:06

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to='services/'),
        ),
    ]
